#!/bin/bash

set -e

cd "$(dirname "$0")"

time taskset -c 0-15 ../run.sh \
    ../data/customer.txt ../data/orders.txt ../data/lineitem.txt \
    6 \
    BUILDING 1995-03-29 1995-03-27 5 \
    XXX 1995-03-29 1995-03-27 5 \
    BUILDING 1995-02-29 1995-04-27 10 \
    YYY 1995-02-29 1995-04-27 10 \
    BUILDING 1995-03-28 1995-04-27 2 \
    ZZZ 1995-03-28 1995-04-27 2 \
    \
    >"$(basename "$0").stdout"

echo
diff "$(basename "$0").stdout" "$(basename "$0").result"

