#!/bin/bash

set -e

cd "$(dirname "$0")"

time taskset -c 0-15 ../run.sh \
    ../data/customer.txt ../data/orders.txt ../data/lineitem.txt \
    1 \
    AUTOMOBILE 1999-03-23 1998-08-29 71068 \
    \
    >"$(basename "$0").stdout"

echo
diff "$(basename "$0").stdout" "$(basename "$0").result"

