#!/bin/bash

set -e

cd "$(dirname "$0")"

time taskset -c 0-15 ../run.sh \
    ../data/customer.txt ../data/orders.txt ../data/lineitem.txt \
    1 \
    HOUSEHOLD  1992-01-11 1990-04-28 85235 \
    \
    >"$(basename "$0").stdout"

echo
diff "$(basename "$0").stdout" "$(basename "$0").result"

