#!/bin/bash

set -e

cd "$(dirname "$0")"

time ../src/BDCI19.out \
    ../data/customer.txt ../data/orders.txt ../data/lineitem.txt \
    3 \
    BUILDING 1995-03-29 1995-03-27 5 \
    BUILDING 1995-02-29 1995-04-27 10 \
    BUILDING 1995-03-28 1995-04-27 2 \
    \
    | tee "$(basename "$0").stdout"


diff "$(basename "$0").stdout" "$(basename "$0").result"

