#!/bin/bash

set -e

cd "$(dirname "$0")"

time taskset -c 0-15 ../run.sh \
    ../data/customer.txt ../data/orders.txt ../data/lineitem.txt \
    1 \
    BUILDING 1998-08-02 1992-01-02 5 \
    \
    >"$(basename "$0").stdout"

echo
diff "$(basename "$0").stdout" "$(basename "$0").result"

